# Generated by Django 4.2.11 on 2024-03-17 11:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelecomPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('1', 'Platinum365'), ('2', 'Gold180'), ('3', 'Silver90')], max_length=20)),
                ('cost', models.IntegerField(choices=[(1, 'Plan_499'), (2, 'Plan_299'), (3, 'Plan_199')])),
                ('validity', models.IntegerField(choices=[(1, 'Validity_365'), (2, 'Validity_180'), (3, 'Validity_90')])),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('aadhar_number', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)])),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('plan_activation_date', models.DateField(null=True)),
                ('plan_status', models.BooleanField(default=False)),
                ('current_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tcms_app.telecomplan')),
            ],
        ),
    ]
