# Generated by Django 4.2.11 on 2024-03-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_app', '0003_alter_customer_plan_activation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='plan_activation_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
